name: CI

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**.md'
      - 'README.md'      
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'README.md' 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --shm-size 2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio fastapi
        pip install -r requirements.txt
        playwright install
    
    - name: Start App and Run tests
      run: |
        nohup python service.py &
        sleep 5
        xvfb-run pytest